""" TESTING DATA: Wikipedia Biographies """

biographies = {
    'No Input': '',

    'King Arthur': """King Arthur (Welsh: Brenin Arthur, Cornish: Arthur Gernow, Breton: Roue Arzhur) was a legendary British leader who, according to medieval histories and romances, led the defence of Britain against Saxon invaders in the late 5th and early 6th centuries. The details of Arthur's story are mainly composed of folklore and literary invention, and modern historians generally agree that he is unhistorical.[2][3] The sparse historical background of Arthur is gleaned from various sources, including the Annales Cambriae, the Historia Brittonum, and the writings of Gildas. Arthur's name also occurs in early poetic sources such as Y Gododdin.[4]
Arthur is a central figure in the legends making up the Matter of Britain. The legendary Arthur developed as a figure of international interest largely through the popularity of Geoffrey of Monmouth's fanciful and imaginative 12th-century Historia Regum Britanniae (History of the Kings of Britain).[5] In some Welsh and Breton tales and poems that date from before this work, Arthur appears either as a great warrior defending Britain from human and supernatural enemies or as a magical figure of folklore, sometimes associated with the Welsh otherworld Annwn.[6] How much of Geoffrey's Historia (completed in 1138) was adapted from such earlier sources, rather than invented by Geoffrey himself, is unknown.
Although the themes, events and characters of the Arthurian legend varied widely from text to text, and there is no one canonical version, Geoffrey's version of events often served as the starting point for later stories. Geoffrey depicted Arthur as a king of Britain who defeated the Saxons and established a vast empire. Many elements and incidents that are now an integral part of the Arthurian story appear in Geoffrey's Historia, including Arthur's father Uther Pendragon, the magician Merlin, Arthur's wife Guinevere, the sword Excalibur, Arthur's conception at Tintagel, his final battle against Mordred at Camlann, and final rest in Avalon.
The 12th-century French writer Chrétien de Troyes, who added Lancelot and the Holy Grail to the story, began the genre of Arthurian romance that became a significant strand of medieval literature. In these French stories, the narrative focus often shifts from King Arthur himself to other characters, such as various Knights of the Round Table. Arthurian literature thrived during the Middle Ages but waned in the centuries that followed until it experienced a major resurgence in the 19th century. In the 21st century, the legend lives on, not only in literature but also in adaptations for theatre, film, television, comics and other media.""",

    'Romeo': """Romeo Montague is the protagonist of William Shakespeare's tragedy, The Tragedy of Romeo and Juliet. The son of Lord Montague and his wife, Lady Montague, he secretly loves and marries Juliet, a member of the rival House of Capulet, through a priest named Friar Laurence. Forced into exile after slaying Juliet's cousin, Tybalt, in a duel, Romeo commits suicide upon hearing falsely of Juliet's death.
The character's origins can be traced as far back as Pyramus, who appears in Ovid's Metamorphoses, but the first modern incarnation of Romeo is Mariotto in the 33rd of Masuccio Salernitano's Il Novellino (1476). This story was reworked in 1524 by Luigi da Porto as Giulietta e Romeo (published posthumously in 1531). Da Porto named the character Romeo Montecchi and his storyline is near-identical to Shakespeare's adaptation.[1] Since no 16th-century direct English translation of Giulietta e Romeo is known, Shakespeare's main source is thought to be Arthur Brooke's English verse translation of a French translation of a 1554 adaptation by Matteo Bandello.[2] Although both Salernitano and da Porto claimed that their stories had historical basis, there is little evidence that this is the case.
Romeo, an only child like Juliet, is one of the most important characters of the play, and has a consistent presence throughout it. His role as an idealistic lover has led the word "Romeo" to become a synonym for a passionate male lover in various languages. Although often treated as such, it is not clear that "Montague" is a surname in the modern sense.""",

    'Stevie Nicks': """Stephanie Lynn Nicks (born May 26, 1948)[1] is an American singer and songwriter. Nicks is a songwriter and vocalist with Fleetwood Mac, and also performs solo. She is known for her distinctive voice, mystical stage persona and poetic, symbolic lyrics.[2] Her work both as a member of Fleetwood Mac and as a solo artist has produced over 40 top 50 hits and sold over 120 million records, making them one of the best-selling music bands of all time.[3]
Nicks joined Fleetwood Mac in 1975 along with her then-boyfriend Lindsey Buckingham. Rumours, Fleetwood Mac's second album after the incorporation of Nicks and Buckingham, was the best-selling album of the year of its release and to date has sold over 40 million copies worldwide, making it the fifth biggest-selling studio album of all time. The album remained at number one on the American albums chart for 31 weeks and reached number one in other countries. The album won the Grammy Award for Album of the Year in 1978. It produced four U.S. Billboard Hot 100 top-ten singles, with Nicks's "Dreams" being the band's first and only Billboard Hot 100 number-one hit.
In 1981, while remaining a member of Fleetwood Mac, Nicks began her solo career, releasing the studio album Bella Donna, which topped the Billboard 200 and has reached multiplatinum status.[4] She has released eight solo studio albums.
Nicks was named one of the 100 Greatest Songwriters of All Time by Rolling Stone.[5] She is the only woman to have been inducted twice into the Rock and Roll Hall of Fame, as a member of Fleetwood Mac in 1998 and as a solo artist in 2019.[6] She has garnered eight Grammy Award[7] nominations and two American Music Award nominations as a solo artist. She has won numerous awards with Fleetwood Mac, including a Grammy Award and five Grammy Award nominations.""",

    'Vincent van Gogh': """Vincent Willem van Gogh (Dutch: [ˈvɪnsənt ˈʋɪləm vɑŋ ˈɣɔx] (About this soundlisten);[note 1] 30 March 1853 – 29 July 1890) was a Dutch post-impressionist painter who is among the most famous and influential figures in the history of Western art. In just over a decade, he created about 2,100 artworks, including around 860 oil paintings, most of which date from the last two years of his life. They include landscapes, still lifes, portraits and self-portraits, and are characterised by bold colours and dramatic, impulsive and expressive brushwork that contributed to the foundations of modern art. He was not commercially successful, and his suicide at 37 came after years of mental illness, depression and poverty.
Born into an upper-middle-class family, Van Gogh drew as a child and was serious, quiet, and thoughtful. As a young man he worked as an art dealer, often travelling, but became depressed after he was transferred to London. He turned to religion and spent time as a Protestant missionary in southern Belgium. He drifted in ill health and solitude before taking up painting in 1881, having moved back home with his parents. His younger brother Theo supported him financially, and the two kept a long correspondence by letter. His early works, mostly still lifes and depictions of peasant labourers, contain few signs of the vivid colour that distinguished his later work. In 1886, he moved to Paris, where he met members of the avant-garde, including Émile Bernard and Paul Gauguin, who were reacting against the Impressionist sensibility. As his work developed he created a new approach to still lifes and local landscapes. His paintings grew brighter in colour as he developed a style that became fully realised during his stay in Arles in the south of France in 1888. During this period he broadened his subject matter to include series of olive trees, wheat fields and sunflowers.
Van Gogh suffered from psychotic episodes and delusions and though he worried about his mental stability, he often neglected his physical health, did not eat properly and drank heavily. His friendship with Gauguin ended after a confrontation with a razor when, in a rage, he severed part of his own left ear. He spent time in psychiatric hospitals, including a period at Saint-Rémy. After he discharged himself and moved to the Auberge Ravoux in Auvers-sur-Oise near Paris, he came under the care of the homeopathic doctor Paul Gachet. His depression continued and on 27 July 1890, Van Gogh shot himself in the chest with a Lefaucheux revolver.[6] He died from his injuries two days later.
Van Gogh was unsuccessful during his lifetime, and he was considered a madman and a failure. He became famous after his suicide and exists in the public imagination as a misunderstood genius, the artist "where discourses on madness and creativity converge".[7] His reputation began to grow in the early 20th century as elements of his painting style came to be incorporated by the Fauves and German Expressionists. He attained widespread critical, commercial and popular success over the ensuing decades, and he is remembered as an important but tragic painter, whose troubled personality typifies the romantic ideal of the tortured artist. Today, Van Gogh's works are among the world's most expensive paintings to have ever sold, and his legacy is honoured by a museum in his name, the Van Gogh Museum in Amsterdam, which holds the world's largest collection of his paintings and drawings.""",

    'Pablo Picasso': """Pablo Diego José Francisco de Paula Juan Nepomuceno María de los Remedios Cipriano de la Santísima Trinidad Ruiz y Picasso[a] (UK: /ˈpæbloʊ pɪˈkæsoʊ/, US: /ˈpɑːbloʊ pɪˈkɑːsoʊ, -ˈkæs-/,[2][3][4] Spanish: [ˈpaβlo piˈkaso]; 25 October 1881 – 8 April 1973) was a Spanish painter, sculptor, printmaker, ceramicist and theatre designer who spent most of his adult life in France. Regarded as one of the most influential artists of the 20th century, he is known for co-founding the Cubist movement, the invention of constructed sculpture,[5][6] the co-invention of collage, and for the wide variety of styles that he helped develop and explore. Among his most famous works are the proto-Cubist Les Demoiselles d'Avignon (1907), and Guernica (1937), a dramatic portrayal of the bombing of Guernica by German and Italian airforces during the Spanish Civil War.
Picasso demonstrated extraordinary artistic talent in his early years, painting in a naturalistic manner through his childhood and adolescence. During the first decade of the 20th century, his style changed as he experimented with different theories, techniques, and ideas. After 1906, the Fauvist work of the slightly older artist Henri Matisse motivated Picasso to explore more radical styles, beginning a fruitful rivalry between the two artists, who subsequently were often paired by critics as the leaders of modern art.[7][8][9][10]
Picasso's work is often categorized into periods. While the names of many of his later periods are debated, the most commonly accepted periods in his work are the Blue Period (1901–1904), the Rose Period (1904–1906), the African-influenced Period (1907–1909), Analytic Cubism (1909–1912), and Synthetic Cubism (1912–1919), also referred to as the Crystal period. Much of Picasso's work of the late 1910s and early 1920s is in a neoclassical style, and his work in the mid-1920s often has characteristics of Surrealism. His later work often combines elements of his earlier styles.
Exceptionally prolific throughout the course of his long life, Picasso achieved universal renown and immense fortune for his revolutionary artistic accomplishments, and became one of the best-known figures in 20th-century art.""",

    'Aleister Crowley': """Aleister Crowley (/ˈæleɪstər ˈkroʊli/; born Edward Alexander Crowley; 12 October 1875 – 1 December 1947) was an English occultist, ceremonial magician, poet, painter, novelist, and mountaineer. He founded the religion of Thelema, identifying himself as the prophet entrusted with guiding humanity into the Æon of Horus in the early 20th century. A prolific writer, he published widely over the course of his life.
Born to a wealthy family in Royal Leamington Spa, Warwickshire, Crowley rejected his parents' fundamentalist Christian Plymouth Brethren faith to pursue an interest in Western esotericism. He was educated at Trinity College at the University of Cambridge, where he focused his attentions on mountaineering and poetry, resulting in several publications. Some biographers allege that here he was recruited into a British intelligence agency, further suggesting that he remained a spy throughout his life. In 1898 he joined the esoteric Hermetic Order of the Golden Dawn, where he was trained in ceremonial magic by Samuel Liddell MacGregor Mathers and Allan Bennett. Moving to Boleskine House by Loch Ness in Scotland, he went mountaineering in Mexico with Oscar Eckenstein, before studying Hindu and Buddhist practices in India. He married Rose Edith Kelly and in 1904 they honeymooned in Cairo, Egypt, where Crowley claimed to have been contacted by a supernatural entity named Aiwass, who provided him with The Book of the Law, a sacred text that served as the basis for Thelema. Announcing the start of the Æon of Horus, The Book declared that its followers should "Do what thou wilt" and seek to align themselves with their True Will through the practice of magick.
After an unsuccessful attempt to climb Kanchenjunga and a visit to India and China, Crowley returned to Britain, where he attracted attention as a prolific author of poetry, novels, and occult literature. In 1907, he and George Cecil Jones co-founded an esoteric order, the A∴A∴, through which they propagated Thelema. After spending time in Algeria, in 1912 he was initiated into another esoteric order, the German-based Ordo Templi Orientis (O.T.O.), rising to become the leader of its British branch, which he reformulated in accordance with his Thelemite beliefs. Through the O.T.O., Thelemite groups were established in Britain, Australia, and North America. Crowley spent the First World War in the United States, where he took up painting and campaigned for the German war effort against Britain, later revealing that he had infiltrated the pro-German movement to assist the British intelligence services. In 1920 he established the Abbey of Thelema, a religious commune in Cefalù, Sicily where he lived with various followers. His libertine lifestyle led to denunciations in the British press, and the Italian government evicted him in 1923. He divided the following two decades between France, Germany, and England, and continued to promote Thelema until his death.
Crowley gained widespread notoriety during his lifetime, being a recreational drug experimenter, bisexual, and an individualist social critic. Crowley has remained a highly influential figure over Western esotericism and the counterculture, and continues to be considered a prophet in Thelema. He is the subject of various biographies and academic studies.""",

    'Tori Amos': """Myra Ellen Tori Amos (born August 22, 1963)[2] is an American singer-songwriter and pianist. She is a classically trained musician with a mezzo-soprano vocal range.[9] Having already begun composing instrumental pieces on piano, Amos won a full scholarship to the Peabody Institute at Johns Hopkins University at the age of five, the youngest person ever to have been admitted. She was expelled at the age of 11 for what Rolling Stone described as "musical insubordination".[10] Amos was the lead singer of the short-lived 1980s pop group Y Kant Tori Read before achieving her breakthrough as a solo artist in the early 1990s. Her songs focus on a broad range of topics, including sexuality, feminism, politics and religion.
Her charting singles include "Crucify", "Silent All These Years", "God", "Cornflake Girl", "Caught a Lite Sneeze", "Professional Widow", "Spark", "1000 Oceans", "Flavor" and "A Sorta Fairytale", her most commercially successful single in the U.S. to date.[11] Amos has received five MTV VMA nominations, eight Grammy Award nominations, and won an Echo Klassik award for her Night of Hunters classical crossover album. She is listed on VH1's 1999 "100 Greatest Women of Rock and Roll" at #71.[12]""",

    'Luke Skywalker': """Luke Skywalker is a fictional character and the main protagonist of the original film trilogy of the Star Wars franchise created by George Lucas. Portrayed by Mark Hamill, Luke first appeared in Star Wars (1977),[a] and he returned in The Empire Strikes Back (1980) and Return of the Jedi (1983). Three decades later, he portrayed the character in the Star Wars sequel trilogy, appearing in all three films: The Force Awakens (2015), The Last Jedi (2017), and The Rise of Skywalker (2019).
In the original Star Wars trilogy, Luke Skywalker represents the hero archetype of "the young man, called to adventure, the hero going out facing the trials and ordeals, and coming back after his victory with a boon for the community".[3]""",

    'Florence Nightingale': """Florence Nightingale /ˈnaɪtɪŋɡeɪl/, OM, RRC, DStJ (12 May 1820 – 13 August 1910) was an English social reformer, statistician and the founder of modern nursing. Nightingale came to prominence while serving as a manager and trainer of nurses during the Crimean War, in which she organised care for wounded soldiers.[3] She gave nursing a favourable reputation and became an icon of Victorian culture, especially in the persona of "The Lady with the Lamp" making rounds of wounded soldiers at night.[4][5]""",

    'Lewis and Clark': """Meriwether Lewis (August 18, 1774 – October 11, 1809) was an American explorer, soldier, politician, and public administrator, best known for his role as the leader of the Lewis and Clark Expedition, also known as the Corps of Discovery, with William Clark. Their mission was to explore the territory of the Louisiana Purchase, establish trade with, and sovereignty over the natives near the Missouri River, and claim the Pacific Northwest and Oregon Country for the United States before European nations.
William Clark (August 1, 1770 – September 1, 1838) was an American explorer, soldier, Indian agent, and territorial governor.[1] A native of Virginia, he grew up in prestatehood Kentucky before later settling in what became the state of Missouri. Clark was a planter and slaveholder.[2]
Along with Meriwether Lewis, Clark helped lead the Lewis and Clark Expedition of 1804 to 1806 across the Louisiana Purchase to the Pacific Ocean, and claimed the Pacific Northwest for the United States.[3] Before the expedition, he served in a militia and the United States Army. Afterward, he served in a militia and as governor of the Missouri Territory. From 1822 until his death in 1838, he served as Superintendent of Indian Affairs.""",

}
