""" TRAINING DATA: Based on Ten of Carl Jung's Archetypes """

archetypes = {
    "The Hero": {
        "Motto": "Where there’s a will, there’s a way",
        "Desire": "to prove one’s worth through courageous acts",
        "Goal": "expert mastery in a way that improves the world",
        "Strategy": "to be as strong and competent as possible",
        "Weakness": "arrogance, always needing another battle to fight",
        "Talent": "competence and courage",
        "Description": "The Hero is also known as: The warrior, crusader, rescuer, superhero, the soldier, dragon slayer, the winner and the team player.",
    },
    "The Caregiver": {
        "Motto": "Love your neighbour as yourself",
        "Desire": "to protect and care for others",
        "Goal": "to help others",
        "Strategy": "doing things for others",
        "Weakness": "martyrdom and being exploited",
        "Talent": "compassion, generosity",
        "Description": "The Caregiver is also known as: The saint, altruist, parent, helper, supporter.",
    },
    "The Explorer": {
        "Motto": "Don’t fence me in",
        "Desire": "the freedom to find out who you are through exploring the world",
        "Goal": "to experience a better, more authentic, more fulfilling life",
        "Strategy": "journey, seeking out and experiencing new things, escape from boredom",
        "Weakness": "aimless wandering, becoming a misfit",
        "Talent": "autonomy, ambition, being true to one's soul",
        "Description": "The explorer is also known as: The seeker, iconoclast, wanderer, individualist, pilgrim.",
    },
    "The Rebel": {
        "Motto": "Rules are made to be broken",
        "Desire": "revenge or revolution",
        "Goal": "to overturn what isn’t working",
        "Strategy": "disrupt, destroy, or shock",
        "Weakness": "crossing over to the dark side, crime",
        "Talent": "outrageousness, radical freedom",
        "Description": "The Outlaw is also known as: The rebel, revolutionary, wild man, the misfit, or iconoclast.",
    },
    "The Lover": {
        "Motto": "You’re the only one",
        "Desire": "intimacy and experience",
        "Goal": "being in a relationship with the people, work and surroundings they love",
        "Strategy": "to become more and more physically and emotionally attractive",
        "Weakness": "outward-directed desire to please others at risk of losing own identity",
        "Talent": "passion, gratitude, appreciation, and commitment",
        "Description": "The Lover is also known as: The partner, friend, intimate, enthusiast, sensualist, spouse, team-builder.",
    },
    "The Artist": {
        "Motto": "If you can imagine it, it can be done",
        "Desire": "to create things of enduring value",
        "Goal": "to realize a vision",
        "Strategy": "develop artistic control and skill, to create culture, express own vision",
        "Weakness": "perfectionism, bad solutions",
        "Talent": "creativity and imagination",
        "Description": "The Creator is also known as: The artist, inventor, innovator, musician, writer or dreamer.",
    },
    "The Entertainer": {
        "Motto": "You only live once",
        "Desire": "to live in the moment with full enjoyment",
        "Goal": "to have a great time and lighten up the world",
        "Strategy": "play, make jokes, be funny",
        "Weakness": "frivolity, wasting time",
        "Talent": "joy",
        "Description": "The Entertainer is also known as: The fool, jester, trickster, joker, practical joker or comedian.",
    },
    "The Sage": {
        "Motto": "The truth will set you free",
        "Desire": "to find the truth.",
        "Goal": "to use intelligence and analysis to understand the world.",
        "Strategy": "seeking out information and knowledge; self-reflection and understanding thought processes.",
        "Weakness": "can study details forever and never act.",
        "Talent": "wisdom, intelligence.",
        "Description": "The Sage is also known as: The expert, scholar, detective, advisor, thinker, philosopher, academic, researcher, thinker, planner, professional, mentor, teacher, contemplative.",
    },
    "The Magician": {
        "Motto": "I make things happen.",
        "Desire": "understanding the fundamental laws of the universe",
        "Goal": "to make dreams come true",
        "Strategy": "develop a vision and live by it",
        "Weakness": "becoming manipulative",
        "Talent": "finding win-win solutions",
        "Description": "The Magician is also known as:The visionary, catalyst, inventor, charismatic leader, shaman, healer, medicine man.",
    },
    "The Ruler": {
        "Motto": "Power is everything.",
        "Desire": "control",
        "Goal": "create a prosperous, successful family or community",
        "Strategy": "exercise power",
        "Weakness": "being authoritarian, unable to delegate",
        "Talent": "responsibility, leadership",
        "Description": "The Ruler is also known as: The boss, leader, aristocrat, king, queen, politician, role model, manager or administrator.",
    },
}

directions = {
    'North': {'Text': "north northern northerly"},
    'South': {'Text': "south southern southerly"},
    'East': {'Text': "east eastern easterly"},
    'West': {'Text': "west western westerly"},
}
